### ISSUE TITLE
command 'extension.NyanCatReload' not found

### ISSUE THREAD

**Issue by andbuitra** [zhengrenzhe/vscode-Nyan-Cat#1]
Hello.

I just installed the extension but when trying to reload it shows the error "command 'extension.NyanCatReload' not found". Same with the refresh one "command 'extension.NyanCatRefresh' not found"

Edit:

It doesn't work at all, btw.

Installed version: The marketplace one
VSCode Version: 1.19.1

**Comment by zhengrenzhe** [comment]
What operating system do you use?
Are you installing for the first time or Update to the latest version?
You installed the version is 0.0.5?

**Comment by andbuitra** [comment]
I'm using elementaryOS Loki (Ubuntu 16.04).

Installing for the first time.

Installed version is 0.0.5

**Comment by zhengrenzhe** [comment]
got, I have to test the problem on elementaryos, it needs some time, before i fixed the bug, you can uninstall the extension.

**Comment by zhengrenzhe** [comment]
Because of the VSCode extension have no permissions to modify the VSCode source code on linux,  it leds this problem, so you can run VSCode with sudo, for example
```
sudo code --user-data-dir=~
```
then rerun`Nyan Cat: refresh status bar` or other command,  and close this VSCode instance, then reopen vscode by ordinary user, you can see the command came into effect.

**Comment by andbuitra** [comment]
Hi, I was traveling therefore I wasn't able to check this.

Will try and tell you asap.

**Comment by andbuitra** [comment]
Yes, that worked perfectly. I now have the nice kitty on the status bar. Thanks a lot!

**Comment by jchen43** [comment]
Trying this on Windows 10 with the same issue as the ticket.

Tried running as admin with a --user-data-dir set to root(C:\.vscode\).

Any thoughts on trying to debug this?

**Comment by MuhammadimYusoff** [comment]
First time install and very disappointed :(

says the same error, I am on macOS and I just installed for the extension, the error came out and I found this thread but cant even fix it. :(

*OS: macOS Catalina
*Nyan version: 0.0.6
*VSCode: Version: 1.42.0
Electron: 6.1.6
OS: Darwin x64 19.3.0

HELPPPPP

**Comment by Noemi-** [comment]
+1, on mac 10.15.1 
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

**Comment by surocham** [comment]
please, i need nyan cat 😿

**Comment by lucasvabrantes** [comment]
Not working on Mac Os Ventura! Please, guys. Nyan Cat is a gift for the humanity!

**Comment by definesfineout** [comment]
Doesn't work on Windows 10. Running in admin doesn't help.
